### ISSUE TITLE
Couldn't get it working

### ISSUE THREAD

**Issue by bazaglia** [sourcey/spectacle#10]
When I run `spectacle swagger.json` I get this:

```
$ spectacle swagger.json 
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/andre/.nvm/versions/node/v6.9.1/lib/node_modules/spectacle-docs/swagger.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andre/.nvm/versions/node/v6.9.1/lib/node_modules/spectacle-docs/bin/spectacle-cli.js:50:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by kalafut** [comment]
As do I.

**Comment by auscaster** [comment]
Must be a regression in the last version, sorry for the trouble. I'll push
through a fix in the next couple of hours (unless someone beats me to it :))

**Comment by aep** [comment]
if you're running into that issue, use:
`spectacle -d $PWD/swagger.json`
