### ISSUE TITLE
How to run this app on local machine and github pages aswell

### ISSUE THREAD

**Issue by vinodkumarmarupu** [sourcey/spectacle#113]
E:\APIDoc\spectacle-master\spectacle-master>spectacle spectacle -s
module.js:471
    throw err;
    ^

Error: Cannot find module 'E:\APIDoc\spectacle-master\spectacle-master\spectacle
'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadData (C:\Users\miracle\AppData\Roaming\npm\node_modules\spectacle-doc
s\index.js:53:46)
    at module.exports (C:\Users\miracle\AppData\Roaming\npm\node_modules\spectac
le-docs\index.js:56:70)
    at Object.<anonymous> (C:\Users\miracle\AppData\Roaming\npm\node_modules\spe
ctacle-docs\bin\spectacle.js:35:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

I got this error on my machine.

**Comment by yyamano** [comment]
@vinodkumarmarupu You need to pass a spec file name as an argument. Could you try:

```
spectacle test\fixtures\cheese.yml -s 
```

**Comment by vinodkumarmarupu** [comment]
Thank you worked for me. How to run on Github?

**Comment by yyamano** [comment]
@vinodkumarmarupu I don't think you can run the spectacle server on github. Instead you can upload files in public directory to github.

**Comment by vinodkumarmarupu** [comment]
If we upload the public directory to GitHub what it will do?

**Comment by auscaster** [comment]
Hi Vinod, please look into Github pages https://pages.github.com/

You can use github to host the static HTML documentation, but you need to
generate the documentation locally.

**Comment by vinodkumarmarupu** [comment]
Thank you Kam, I will work on that.
