### ISSUE TITLE
Unable to run with Docker: request-sync is deprecated, use sync-request

### ISSUE THREAD

**Issue by elifarley** [sourcey/spectacle#123]
Hi, 
I wasn't able to run Spectacle from within Docker. Did I miss something?

Here's what I did:

```
docker run -it --rm -v "$PWD":/data sourcey/spectacle /bin/sh

/opt # spectacle -d -l /data/doc/logo-small.png /data/doc/my-api.json
request-sync is deprecated, use sync-request
/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:169
    if(val.$ref) {
          ^

TypeError: Cannot read property '$ref' of null
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:169:11)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/app/lib/preprocessor.js:76:3)
    at loadData (/usr/local/lib/node_modules/spectacle-docs/index.js:52:72)
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/index.js:56:70)
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/bin/spectacle.js:35:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
```

**Comment by auscaster** [comment]
Hello, docker images have been updated and now use semantic versioning.

**Comment by gianniszach** [comment]
Hello, I'm using the latest docker image and I'm receiving the reported error. Can you help me resolve it?
