### ISSUE TITLE
Description in security definition fails to render

### ISSUE THREAD

**Issue by mcveat** [sourcey/spectacle#126]
Following security definition:
```
"securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "in": "header",
      "name": "authorization",
      "description": "will not render"
    }
  }
```

fails to render with exception: 
```
Unhandled rejection Error: marked(): input parameter is of type [object String], string expected
    at marked (node_modules/marked/lib/marked.js:1242:11)
    at Object.markdown (node_modules/spectacle-docs/app/lib/common.js:20:17)
    at String.module.exports (node_modules/spectacle-docs/app/helpers/md.js:14:21)
```

There seems to be an issue with reference to `this` on line 29:

https://github.com/sourcey/spectacle/blob/c7a4f8b85f77d745fab2fea4c6faf52fc03dcbb1/app/views/partials/swagger/securityDefinitions.hbs#L27-L33

 because replacing that block with:
```
           {{#with this as | parent | }}
                {{#each this}}
                  {{#ifin @key "['type', 'scopes']"}}
                  {{else}}
                    <div class="prop-row security-definition-property">
                      <div class="prop-name">
                        <div class="prop-title security-definition-property-name">{{@key}}</div>
                      </div>
                      <div class="prop-value security-definition-property-type">
                        {{#ifeq @key 'description'}}
                            {{md parent.description }}
                        {{else}}
                            {{this}}
                        {{/ifeq}}
                      </div>
                    </div>
                  {{/ifin}}
                {{/each}}
            {{/with}}
```

renders it correctly.

Unfortunately I don't know handlebars that well to figure out a solution. Workaround above feels too much of a hack to be pull request worthy. Hope you can help me fix that.

**Comment by auscaster** [comment]
I was able to reproduce the error and this one is fixed in 1.0.1 :)
