### ISSUE TITLE
Docker image should use NodeJs 8+

### ISSUE THREAD

**Issue by oliviermaridat** [sourcey/spectacle#174]
Hello!

Thanks for all the hard work.

I understood that due to the version of Saas that is used, NodeJs 8+ is required to run spectacle (see at least #156, #157, #114). But the Docker image "sourcey/spectacle" is provided with v7.5.0 which leads to the above well-known error.

Is it possible to ship the Docker image with NodeJs 8? Or is it possible to remove this dependency to NodeJs 8+ by using another Saas version? Thanks!

```
request-sync is deprecated, use sync-request                                                                                                                                                 
Loading "sass.js" tasks...ERROR                                                                                                                                                              
>> SyntaxError: Unexpected token (                                                                                                                                                           
Task error: Error: Task "sass:foundation_scss" not found.
    at Task.run (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:179:28)                                                                                     
    at Object.thisTask.fn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/grunt/task.js:82:16)                                                                           
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:301:30)                                                                           
    at Task.runTaskFn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:251:24)                                                                               
    at Task.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:300:12)                                                                             
    at Task.start (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:309:5)                                                                                    
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/index.js:169:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/bin/spectacle.js:35:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
Task error: Error: Task "sass:scss" not found.
    at Task.run (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:179:28)                                                                                     
    at Object.thisTask.fn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/grunt/task.js:82:16)                                                                           
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:300:12)
    at Task.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:230:9)
    at Task.runTaskFn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:257:7)
    at Task.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:300:12)
    at Task.start (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:309:5)
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/index.js:169:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/bin/spectacle.js:35:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Running "concat:js" (concat) task

Running "uglify:js" (uglify) task
>> 1 file created 6.79 kB → 3 kB

Running "clean:html" (clean) task
Unhandled rejection Error: Task "sass:foundation_scss" not found.
    at Task.run (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:179:28)
    at Object.thisTask.fn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:300:12)
    at Task.start (/usr/local/lib/node_modules/spectacle-docs/node_modules/grunt/lib/util/task.js:309:5)
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/index.js:169:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/bin/spectacle.js:35:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)

>> 1 path cleaned.

Running "compile-handlebars:compile" (compile-handlebars) task

Running "predentation" task

Running "prettify:index" (prettify) task
>> File "/app/public/index.html" prettified.
All tasks complete
```

**Comment by abrongersma** [comment]
Hi @oliviermaridat 

The Docker image published to dockerhub is a bit out of date. If you clone this repo and build the docker container from source you'll be running the container using the `node:8-alpine` image. 

```docker build . -t spectacle:latest```

**Comment by auscaster** [comment]
Closing as superseded. This repo has been rewritten; `spectacle-docs` is no longer maintained and now hosts [Sourcey](https://sourcey.com), a static docs platform on Astro + Preact. If it still bites in the new build, please file fresh.
