### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by LGMAM** [sourcey/spectacle#34]
Just installed from npm:

```
node -v
v0.12.15
```

```
"name": "spectacle-docs",
"version": "0.6.9",
```

When trying to process one file I am getting this error:

```
/usr/lib/node_modules/spectacle-docs/app/lib/config.js:16
                  [path.resolve(options.cacheDir, 'stylesheets/spectacle.css')
                  ^
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/usr/lib/node_modules/spectacle-docs/index.js:29:18)
    at Object.<anonymous> (/usr/lib/node_modules/spectacle-docs/bin/spectacle.js:53:1)
    at Module._compile (module.js:460:26)
```

Any hint ?
Thanks,
Luis

**Comment by auscaster** [comment]
The answer is to upgrade nodejs to support new object syntax. I'm running
v4.2.6

**Comment by LGMAM** [comment]
That did it. 
Thanks,
Luis
