### ISSUE TITLE
No support for `schema.$ref` in response block

### ISSUE THREAD

**Issue by christopherraa** [sourcey/spectacle#46]
When defining the resource block for an endpoint this seems to be parsed without crashing:

``` json
"responses": {
  "200": {
    "description": "The magic",
    "$ref": "#/definitions/Magic"
  }
}
```

This is also parsed without failing:

``` json
"responses": {
  "200": {
    "description": "The magic list",
    "schema": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Magic"
      }
    }
  }
}
```

This however fail spectacularly:

``` json
"responses": {
  "200": {
    "description": "pet response",
    "schema": {
      "$ref": "#/definitions/Pet"
    }
  }
}
```

The error is as follows:
```
Running "sass:foundation_scss" (sass) task

Running "concat:foundation_css" (concat) task
File public/docs/stylesheets/foundation.css created.

Running "sass:scss" (sass) task

Running "concat:css" (concat) task
File public/docs/stylesheets/spectacle.css created.

Running "cssmin:minify" (cssmin) task
>> 2 files created. 124.27 kB → 96.12 kB

Running "concat:js" (concat) task
File public/docs/javascripts/spectacle.js created.

Running "uglify:js" (uglify) task
>> 1 file created.

Running "clean:html" (clean) task
>> 1 path cleaned.

Running "compile-handlebars:compile" (compile-handlebars) task
Task error: [TypeError: Cannot convert undefined or null to object]

Running "predentation" task
Task error: { [Error: ENOENT: no such file or directory, open '/tmp/spectacle-181377bUV6f0YUJkd/api.html']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/spectacle-181377bUV6f0YUJkd/api.html' }

Running "prettify:index" (prettify) task
>> Destination not written because dest file was empty.
All tasks complete
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.common.formatExampleProp (node_modules/spectacle-docs/app/lib/common.js:91:11)
    at Object.common.formatExampleProp (node_modules/spectacle-docs/app/lib/common.js:88:16)
    at Object.common.formatExample (node_modules/spectacle-docs/app/lib/common.js:75:16)
    at Object.module.exports (node_modules/spectacle-docs/app/helpers/printExample.js:5:23)
    at Object.eval (eval at createFunctionContext (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:4:117)
    at main (node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at Object.invokePartial (node_modules/handlebars/dist/cjs/handlebars/runtime.js:273:12)
    at Object.invokePartialWrapper [as invokePartial] (node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at eval (eval at createFunctionContext (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:28)
    at prog (node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:80:11)
    at eval (eval at createFunctionContext (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:31)
```
This can be reproduced using the [PetStore Expanded example file](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore-expanded.json) as provided by the OpenApi Initiative.

This was run with **spectacle-docs 0.7.4** installed with `npm`.
The job definition in the package.json scrips-block looked as follows:

```
"build:docs": "mkdir -p public/docs; spectacle -t public/docs -f pet.html petstore-expanded.json",
```

Am I holding it wrong?

**Comment by bguiz** [comment]
aha @christopherraa I was getting the same error, but wasn't able to figure out from the error message what part of the schema was problematic, thanks for highlighting this.

I'd also like a fix for this!

**Comment by auscaster** [comment]
Hi guys, sorry for the trouble ... fixed in v0.7.5

**Comment by auscaster** [comment]
Also I've added the extended petstore example to fixtures so it can be easily tested against like so `node bin/spectacle test/fixtures/petstore-expanded.json`

**Comment by christopherraa** [comment]
@auscaster Brilliant. That was quick. :) Looking forward to trying it out. If you ever find yourself in Bergen, Norway I'll buy you a `$favorite_beverage`. Cheers!

**Comment by auscaster** [comment]
Might even take you up on that - it will be warm enough to venture that far
north soon! Cheers :)
