### ISSUE TITLE
Exception when model have tree structure

### ISSUE THREAD

**Issue by mczachurski** [sourcey/spectacle#51]
I have model like that:

```json
      "ChapterItemDto":{  
         "type":"object",
         "properties":{  
            "name":{  
               "type":"string"
            },
            "url":{  
               "type":"string"
            },
            "children":{  
               "type":"array",
               "items":{  
                  "$ref":"#/definitions/ChapterItemDto"
               },
               "readOnly":true
            }
         }
      },
```

Thus `ChapterItemDto` has `children` property. This property is an array of `ChapterItemDto` objects. For that construction when I execute spectacle I have following exception:

```
Running "compile-handlebars:compile" (compile-handlebars) task
Task error: RangeError: Maximum call stack size exceeded
    at String.lastIndexOf (native)
    at Object.resolveSchemaReference (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:159:19)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:101:17)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:119:20)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:107:23
    at Array.forEach (native)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:106:35)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:102:18)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:119:20)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:107:23
    at Array.forEach (native)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:106:35)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:102:18)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:119:20)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:107:23
    at Array.forEach (native)
```

Probably there is an infinite loop. 

BTW: Thanks for great application!

**Comment by auscaster** [comment]
This has been fixed on master. Please reopen if the issue persists :)

**Comment by mattosaur** [comment]
I'm still seeing this error, although the line number has changed.

```Running "compile-handlebars:compile" (compile-handlebars) task
Task error: RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at Object.resolveSchemaReference (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:194:15)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:114:17)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:121:25
    at Array.forEach (native)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:119:35)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:131:29
    at Array.forEach (native)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:128:17)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:115:18)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:121:25
    at Array.forEach (native)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:119:35)
    at Object.formatExampleProp (/usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:115:18)
    at /usr/local/lib/node_modules/spectacle-docs/app/lib/common.js:131:29
    at Array.forEach (native)```

**Comment by auscaster** [comment]
Hmmm I tested this today with a circular model reference as above and there were no errors :/

**Comment by auscaster** [comment]
If you would live me to look further please send your schema to auscaster@gmail.com and I will check it out.
