### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by stephencoe** [sourcey/spectacle#65]
Possible related to https://github.com/sourcey/spectacle/issues/46 as the issue is the same but I still see this error when running build or development mode.

`spectacle -l test/fixtures/cheese.png test/fixtures/petstore-expanded.json`

```
All tasks complete
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/app/lib/common.js:115:22
    at Array.forEach (native)
    at Object.formatExampleProp (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/app/lib/common.js:114:17)
    at Object.formatExampleProp (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/app/lib/common.js:102:18)
    at Object.formatExampleProp (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/app/lib/common.js:120:20)
    at Object.formatExample (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/app/lib/common.js:80:19)
    at Object.module.exports (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/app/helpers/printExample.js:5:23)
    at Object.eval [as main] (eval at createFunctionContext (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:4:117)
    at main (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as swagger/print-example] (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at eval (eval at createFunctionContext (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:28)
    at Object.prog [as fn] (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Object.<anonymous> (/Users/stephen/workspace/swagger-node/mydrive/node_modules/spectacle-docs/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)


```

**Comment by alessandroorru** [comment]
I had a similar issue, due to how inheritance is defined.

Basically I had this:
`allOf: 
    - $ref: '#/definitions/BaseObject'
    - properties: 
          something: ...
`

And I had to change it like this:

`allOf: 
    - $ref: '#/definitions/PortfolioOperationItem'
    - type: object
      properties: 
          something: ...
`

**Comment by auscaster** [comment]
I'm currently working on a fix for this guys, please hold tight.

**Comment by auscaster** [comment]
Fix is on npm :)
