### ISSUE TITLE
unable to install via npm

### ISSUE THREAD

**Issue by dneilroth** [sourcey/spectacle#84]
when trying to install with `npm install -g spectacle-docs` with node v6.10.3 on Mac OS  Sierra and I am getting the following error:
```
> http-sync@0.0.5 install /Users/david/.nvm/versions/node/v8.2.1/lib/node_modules/spectacle-docs/node_modules/http-sync
> node-gyp rebuild

  CXX(target) Release/obj.target/curllib/curllib.o
../curllib.cc:26:17: error: expected class name
class CurlLib : ObjectWrap {
                ^
../curllib.cc:59:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/david/.node-gyp/8.2.1/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../curllib.cc:92:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Body(const Arguments& args) {
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/david/.node-gyp/8.2.1/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../curllib.cc:114:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Run(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/david/.node-gyp/8.2.1/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../curllib.cc:38:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value>
      (const v8::internal::Arguments &)' (aka 'v8::Local<v8::Value> (const v8::internal::Arguments &)')
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/david/.node-gyp/8.2.1/include/node/v8.h:5132:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
../curllib.cc:40:42: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
    s_ct = Persistent<FunctionTemplate>::New(t);
                                         ^
/Users/david/.node-gyp/8.2.1/include/node/v8.h:593:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../curllib.cc:40:12: error: too few arguments to function call, expected 2, have 1; did you mean '::CurlLib::New'?
    s_ct = Persistent<FunctionTemplate>::New(t);
           ^~~~~~~~~~
           ::CurlLib::New
../curllib.cc:59:24: note: '::CurlLib::New' declared here
  static Handle<Value> New(const Arguments& args) {
                       ^
../curllib.cc:41:9: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; did you mean to use '.'?
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~^~
        .
../curllib.cc:41:11: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~  ^
../curllib.cc:42:9: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; did you mean to use '.'?
    s_ct->SetClassName(String::NewSymbol("CurlLib"));
    ~~~~^~
        .
../curllib.cc:42:11: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    s_ct->SetClassName(String::NewSymbol("CurlLib"));
    ~~~~  ^
../curllib.cc:42:32: error: no member named 'NewSymbol' in 'v8::String'
    s_ct->SetClassName(String::NewSymbol("CurlLib"));
                       ~~~~~~~~^
../curllib.cc:44:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(s_ct, "run", Run);
                              ^~~~
/Users/david/.node-gyp/8.2.1/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
      ^
/Users/david/.node-gyp/8.2.1/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/david/.node-gyp/8.2.1/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against
      'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/david/.node-gyp/8.2.1/include/node/node.h:286:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
../curllib.cc:45:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(s_ct, "body", Body);
                              ^~~~
/Users/david/.node-gyp/8.2.1/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
      ^
/Users/david/.node-gyp/8.2.1/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/david/.node-gyp/8.2.1/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against
      'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/david/.node-gyp/8.2.1/include/node/node.h:286:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
../curllib.cc:48:21: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; did you mean to use '.'?
                s_ct->GetFunction());
                ~~~~^~
                    .
../curllib.cc:48:23: error: no member named 'GetFunction' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
                s_ct->GetFunction());
                ~~~~  ^
../curllib.cc:47:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("CurlLib"),
                ~~~~~~~~^
../curllib.cc:50:23: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_body_length = NODE_PSYMBOL("body_length");
                      ^
../curllib.cc:51:19: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_headers = NODE_PSYMBOL("headers");
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/curllib/curllib.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/david/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/david/.nvm/versions/node/v8.2.1/bin/node" "/Users/david/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/.nvm/versions/node/v8.2.1/lib/node_modules/spectacle-docs/node_modules/http-sync
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: http-sync@0.0.5 (node_modules/spectacle-docs/node_modules/http-sync):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: http-sync@0.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by pdsullivan** [comment]
I am getting the same error when running `npm install -g spectacle-docs`

node: `v6.9.1`

npm: `5.3.0`

**Comment by auscaster** [comment]
Looks like an issue with http-sync.

Maybe try downgrading your node version until a fix is available.

**Comment by auscaster** [comment]
I have just updated the npm version 0.9.7 which removes the http-sync dependency. Hopefully that clears the way

**Comment by dneilroth** [comment]
that did it! thanks so much for the quick reply @auscaster
